---

  # Create a user to running the zookeeper service.
  - name: Create a User `"{{ zookeeper_user }}"` for all our Hadoop Modules.
    user: name={{ zookeeper_user }} password={{ zookeeper_password }}
