#
# -------------------
#  JDK Setup
# -------------------
#

- hosts: all
  remote_user: ubuntu
  vars:
    java_home: /usr/lib/jvm/java-8-openjdk-amd64/
  tasks:
    - name: JDK | Oracle JDK | Make sure openjdk is uninstalled
      apt: pkg=openjdk-11-jdk state=absent
    - name: "Apt Update"
      become: true
      apt: update_cache=yes upgrade=yes force_apt_get=yes cache_valid_time=3600
    - name: "Install JDK 8"
      become: yes
      apt:
        name: "openjdk-8-jdk"
        state: present
    - name: JDK | Oracle JDK | Add the JDK binaries to the system path (/etc/profile)
      lineinfile: dest=/etc/profile regexp='^JAVA_HOME={{ java_home }}' line="JAVA_HOME={{ java_home }}" state=present

    - name: JDK | Oracle JDK | Add the JDK binaries to the system path (/etc/profile)
      lineinfile: dest=/etc/profile regexp='^PATH=.*JAVA_HOME.*' line="PATH=$PATH:$HOME/bin:$JAVA_HOME/bin" state=present
