---
- name: work on zookeeper node/s
  hosts: zookeepernodes
  remote_user: ubuntu

  roles:
    - jdk
    - zookeeper

- name: work on kafka node/s
  hosts: kafkanodes
  remote_user: ubuntu

  roles:
    - jdk
    - kafka
